#!/bin/sh
# System maintenance
alias kop='sudo $(fc -ln -1)'
alias off='sudo poweroff'
alias reboot='sudo reboot'
alias mdot='git --git-dir=$HOME/.local/dotfiles/ --work-tree=$HOME/'
alias ssys='sudo systemctl'
alias p='ping 1.1.1.1'
alias cd..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../../'
alias rmf='rm -rfv'
alias du='sudo du -sh ./* | sort -rh'
alias paux='ps -auxwf | grep'
alias psg='ps -ef | grep -i $1'
alias nsg='netstat -natp | grep -i $1'

# Package maintenance
alias syu='yay -Syu'
alias sp='sudo pacman'

# Default parameters 
alias c='clear'
alias cp='cp -iv'
alias diff='diff --color'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ip='ip -c'
alias ls='ls -lhNF --color=auto --group-directories-first'
alias mkdir='mkdir -pv'
alias msfconsole='msfconsole -q'
alias mv='mv -iv'
alias rm='rm -iv'
alias urlscan='urlscan -csH'

# Program shortcuts
alias cat='bat -pp'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias gs='git status'
alias l='ls' 
alias ll='ls -a'
alias n='ncmpcpp 2>/dev/null'
alias news='newsboat -q'
alias o='rifle'
alias r='ranger'
alias v='$EDITOR'
alias sv='sudoedit'
alias vp='$EDITOR $_'
alias svp='sudoedit $_'
alias catp='bat -pp $_'
alias scatp='sudo bat -pp $_'
alias pwgen='pass generate --clip'
alias stream='ffmpeg -f x11grab -video_size 2560x1440 -framerate 30 -i $DISPLAY -f alsa -i default -c:v libx264 -preset ultrafast -c:a aac screen.mp4'
alias z='setsid nohup zathura > /tmp/zathuranohup.out 2>&1'
alias hugoserv='hugo server -D --minify --disableFastRender'

# XDG_CONFIG workarounds
alias wget='wget --hsts-file="${XDG_CACHE_HOME}/wget-hsts"'
alias tmux='tmux -f "$XDG_CONFIG_HOME/tmux/tmux.conf"'
alias mbsync='mbsync -c "$XDG_CONFIG_HOME/isync/mbsyncrc"'
alias tor-browser='setsid nohup tor-browser-en --dir=$XDG_CONFIG_HOME/tor > /tmp/tor-browsernohup.out 2>&1'
alias weechat='weechat -d "$XDG_CONFIG_HOME/weechat"'

# Automatic file listing after changing directory
cdls () { builtin cd "$@" && l; }
alias cd='cdls'
alias ..='cd ..'

man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

# Printer
cupsadm() { "${BROWSER}" "http://localhost:631"; }
