#!/bin/sh

ip=$(ip addr | grep 'UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')

[ -n "${BLOCK_BUTTON}" ] && case "${BLOCK_BUTTON}" in
    1) echo $ip | xclip -selection c && notify-send "IP address copied" ;; # left click, copy address
    *) ;;
esac
[ ! -d /sys/class/net/eth0/phydev ] || [ "$(cat /sys/class/net/eth0/operstate)" = 'down' ] && exit

echo "${ip}"
