#!/bin/sh

status=$(checkupdates)
count=$(printf '%s' "${status}" | wc -l)

[ -n "${BLOCK_BUTTON}" ] && case "${BLOCK_BUTTON}" in
    1) notify-send "Installing updates..." && pikaur -Syu --noconfirm > /dev/null 2>&1 && notify-send "Updates installed" ;; # left click, update
    3) notify-send "${status}" ;; # right click, list updates
    *)  ;;
esac

[ "${count}" != 0 ] && echo "${count}"
