#!/bin/sh

# Source xresources
[ -x "$(command -v xrdb || true)" ] && xrdb -merge "${XDG_CONFIG_HOME:?}/xorg/xresources" &

# Increase key speed, set dpms parameters and set wallpaper
[ -x "$(command -v xset || true)" ] && xset r rate 300 50 &
[ -x "$(command -v xset || true)" ] && xset s off -dpms &
[ -x "$(command -v xwallpaper || true)" ] && xwallpaper --zoom "${XDG_CACHE_HOME:?}/wall" &

# Display configuration
[ -x "$(command -v autorandr || true)" ] && autorandr --default &
[ -x "$(command -v redshift || true)" ] && redshift -P -O 4200 &

# Autostart
autostart="dunst mpd unclutter xcompmgr spice-vdagent firefox thunderbird caprine discord signal-desktop spotify"
for program in ${autostart}; do
    pidof -s "${program}" || [ -x "$(command -v "${program}" || true)" ] && setsid -f "${program}"
done >/dev/null 2>&1

# Start WM
[ -x "$(command -v dwmblocks || true)" ] && setsid -f dwmblocks
exec dwm
