#!/bin/sh
# TODO: find a way to terminate autostart applications upon exit from dwm

# Source Xresources
xrdb -merge "$XDG_CONFIG_HOME/xorg/Xresources" &

# Increase key speed, enable compositor and set dpms parameters 
/usr/bin/xset r rate 300 35 &
xcompmgr &
xset s off -dpms &

# Autostart 
[ -f /usr/bin/firefox ] && firefox &

# Display configuration
[ -f /usr/bin/autorandr ] && autorandr --default &
[ -f /usr/bin/redshift ] && redshift -P -O 4200 &

# Daemons
[ -f /usr/bin/crond ] && crond -f "$XDG_CONFIG_HOME/crontab" &
[ -f /usr/bin/dunst ] && dunst &
[ -f /usr/bin/mpd ] && mpd &
[ -f /usr/bin/spice-vdagent ] && spice-vdagent &

# Tray
[ -f /usr/bin/caprine ] && caprine --minimize &
[ -f /usr/bin/discord ] && discord --start-minimized &
[ -f /usr/bin/signal-desktop ] && signal-desktop --start-in-tray &
[ -f /usr/bin/blueman-applet ] && blueman-applet &

# Start WM
#while /usr/bin/xsetroot -name "$(/usr/bin/date || true) $(/usr/bin/uptime | /usr/bin/sed 's/.*,//' || true)"
#do
#    sleep 1
#done &
exec dwm
