#!/bin/sh

# Increase key speed and set dpms parameters
[ -x "$(command -v xset || :)" ] && xset r rate 300 50 &
[ -x "$(command -v xset || :)" ] && xset s off -dpms &

# Display configuration
[ -x "$(command -v autorandr || :)" ] && autorandr --default &
[ -x "$(command -v redshift || :)" ] && redshift -P -O 4200 &
[ -x "$(command -v xwallpaper || :)" ] && xwallpaper --zoom "${XDG_CACHE_HOME:?}/wall" &

# Daemonize cron
[ -x "$(command -v crond || :)" ] && crond -f "${XDG_CONFIG_HOME:?}/crontab" &

# Daemonize mpc idle to update statusbar on mpd events
[ -x "$(command -v mpc || :)" ] && while true; do mpc idle && kill -42 "$(pidof dwmblocks || :)";done &

# Autostart
autostart="dunst mpd unclutter xcompmgr spice-vdagent firefox caprine discord signal-desktop spotify"
for program in ${autostart}; do
    pidof -s "${program}" || [ -x "$(command -v "${program}" || true)" ] && setsid -f "${program}"
done >/dev/null 2>&1

# Start WM
[ -x "$(command -v dwmblocks || true)" ] && setsid -f dwmblocks
exec dwm
